### ISSUE TITLE
impossible to run scritpt RMxxx_rgmii_toolkit.sh

### ISSUE THREAD

**Issue by McMacaron** [iamromulan/quectel-rgmii-configuration-notes#22]
Your guide is running absolutely without issue till the scritpt
adb shell wget -P /tmp https://raw.githubusercontent.com/iamromulan/quectel-rgmii-toolkit/main/RMxxx_rgmii_toolkit.sh
adb shell chmod +x /tmp/RMxxx_rgmii_toolkit.sh
adb shell sh /tmp/RMxxx_rgmii_toolkit.sh

I am not able to make it work in any possible way.

**Comment by iamromulan** [comment]
Yeah that file doesn't exist anymore on the main branch.
I starting to rework the documentation now
Go here and follow the path from there https://github.com/iamromulan/quectel-rgmii-toolkit
